[[constraint]]
  name = "github.com/walterjwhite/go-application/libraries/path"
  version = "0.0.1"

[[constraint]]
  name = "github.com/walterjwhite/go-application/libraries/runner"
  version = "0.0.1"

[[constraint]]
  name = "github.com/walterjwhite/go-application/libraries/screenshot"
  version = "0.0.1"
