[[constraint]]
  name = "github.com/walterjwhite/go-application/libraries/identifier"
  version = "0.0.1"

[[constraint]]
  name = "github.com/walterjwhite/go-application/libraries/logging"
  version = "0.0.1"

[[constraint]]
  name = "github.com/walterjwhite/go-application/libraries/shutdown"
  version = "0.0.1"
